function FileData_Pairs(x)
{
x.t("searching","camod");
x.t("camod","table");
x.t("camod","searches");
x.t("camod","search");
x.t("camod","database");
x.t("table","contents");
x.t("drug","screening");
x.t("mode","camod");
x.t("mode","advanced");
x.t("contents","search");
x.t("advanced","search");
x.t("includes","following");
x.t("simple","search");
x.t("results","drug");
x.t("overview","types");
x.t("searches","searching");
x.t("searches","types");
x.t("searches","section");
x.t("search","mode");
x.t("search","simple");
x.t("search","results");
x.t("search","overview");
x.t("types","camod");
x.t("section","includes");
x.t("database","camod");
x.t("database","search");
x.t("topics","camod");
x.t("following","topics");
x.t("screening","search");
}
