function FileData_Pairs(x)
{
x.t("camod","camod");
x.t("camod","what\u2019s");
x.t("camod","getting");
x.t("camod","what's");
x.t("camod","login");
x.t("describes","new");
x.t("what\u2019s","new");
x.t("new","camod");
x.t("new","features");
x.t("new","hypertext");
x.t("new","page");
x.t("getting","started");
x.t("link","learn");
x.t("abbreviated","directions");
x.t("what's","new");
x.t("features","giving");
x.t("started","camod");
x.t("briefly","describes");
x.t("announces","briefly");
x.t("hypertext","link");
x.t("login","page");
x.t("click","view");
x.t("view","what's");
x.t("page","announces");
x.t("page","click");
x.t("giving","abbreviated");
x.t("using","new");
x.t("directions","using");
x.t("learn","new");
}
