function FileData_Pairs(x)
{
x.t("searching","camod");
x.t("trials","searching");
x.t("trials","populated");
x.t("trials","pre-clinical");
x.t("camod","searches");
x.t("camod","database");
x.t("drug","screening");
x.t("stored","camod.");
x.t("searches","drug");
x.t("populated","data");
x.t("pre-clinical","trials");
x.t("search","pre-clinical");
x.t("types","camod");
x.t("database","types");
x.t("data","stored");
x.t("screening","search");
}
