function FileData_Pairs(x)
{
x.t("searching","camod");
x.t("pre-clinical/clinical","trials");
x.t("trials","drug");
x.t("trials","results");
x.t("lists","center");
x.t("camod","database");
x.t("table","lists");
x.t("table","displays");
x.t("table","body");
x.t("drug","screening");
x.t("displays","name");
x.t("bar","table");
x.t("center","performing");
x.t("details","searching");
x.t("details","clinical");
x.t("trial","status");
x.t("trial","project");
x.t("trial","title");
x.t("status","clinical");
x.t("results","pre-clinical/clinical");
x.t("results","table");
x.t("results","details");
x.t("results","clinical");
x.t("name","clinical");
x.t("search","drug");
x.t("search","results");
x.t("body","table");
x.t("database","drug");
x.t("performing","clinical");
x.t("project","phase");
x.t("title","bar");
x.t("phase","clinical");
x.t("screening","results");
x.t("screening","search");
x.t("clinical","trials");
x.t("clinical","trial");
}
