function FileData_Pairs(x)
{
x.t("responsibilities","process");
x.t("editors","reviewing");
x.t("camod","coordinator");
x.t("camod","administration");
x.t("coordinator","manages");
x.t("functions/grant","privileges");
x.t("include:","assigning");
x.t("review","follow-up");
x.t("review","process");
x.t("review","process.");
x.t("process","camod");
x.t("process","include:");
x.t("process","coordinating");
x.t("manages","model");
x.t("models","review");
x.t("privileges","screeners");
x.t("reviewing","models");
x.t("administration","roles");
x.t("coordinating","review");
x.t("management","coordinating");
x.t("model","review");
x.t("process.","responsibilities");
x.t("screeners","editors");
x.t("assigning","functions/grant");
x.t("roles","management");
}
