function FileData_Pairs(x)
{
x.t("camod","submit");
x.t("dialog","box");
x.t("editing","models");
x.t("new","model");
x.t("link","model");
x.t("add","new");
x.t("add","information");
x.t("logged","camod");
x.t("box","opens");
x.t("edit","models");
x.t("red","hypertext");
x.t("characteristics","dialog");
x.t("opens","add");
x.t("opens","click");
x.t("hypertext","link");
x.t("submitting","editing");
x.t("submitting","models");
x.t("click","add");
x.t("models","logged");
x.t("models","submitting");
x.t("models","page");
x.t("page","opens");
x.t("information","new");
x.t("submit","edit");
x.t("model","red");
x.t("model","characteristics");
}
