function FileData_Pairs(x)
{
x.t("searching","camod");
x.t("four","drug");
x.t("trials","searching");
x.t("trials","populated");
x.t("trials","pre-clinical");
x.t("camod","database");
x.t("drug","screening");
x.t("stored","camod");
x.t("populated","data");
x.t("pre-clinical","trials");
x.t("search","four");
x.t("search","options");
x.t("options","pre-clinical");
x.t("database","drug");
x.t("data","stored");
x.t("screening","search");
}
