function FileData_Pairs(x)
{
x.t("four","drug");
x.t("searching","camod");
x.t("years","nci");
x.t("camod","database");
x.t("description","models");
x.t("drug","screening");
x.t("compounds","potential");
x.t("potential","antitumor");
x.t("tumor","models");
x.t("search","four");
x.t("search","options");
x.t("vivo","animal");
x.t("cancer","chemotherapy");
x.t("antitumor","activity");
x.t("options","searching");
x.t("options","four");
x.t("options","in-vivo");
x.t("activity","detailed");
x.t("detailed","description");
x.t("chemotherapy","reports");
x.t("database","drug");
x.t("in-vivo","anti-tumor");
x.t("anti-tumor","screening");
x.t("thirty","years");
x.t("models","screen");
x.t("models","published");
x.t("screen","compounds");
x.t("data","approximately");
x.t("published","cancer");
x.t("nci","used");
x.t("used","vivo");
x.t("approximately","thirty");
x.t("screening","search");
x.t("screening","data");
x.t("animal","tumor");
}
