function FileData_Pairs(x)
{
x.t("searching","camod");
x.t("camod","database");
x.t("drug","screening");
x.t("summary","page");
x.t("open","in-vivo");
x.t("initially","display");
x.t("link","open");
x.t("details","page");
x.t("compounds","results");
x.t("results","searching");
x.t("results","summary");
x.t("results","initially");
x.t("results","details");
x.t("results","launch");
x.t("results","in-vivo");
x.t("search","drug");
x.t("search","results");
x.t("search","in-vivo");
x.t("display","in-vivo");
x.t("launch","search");
x.t("hypertext","link");
x.t("database","drug");
x.t("click","hypertext");
x.t("in-vivo","drug");
x.t("page","summary");
x.t("page","click");
x.t("page","associated");
x.t("associated","hit");
x.t("screening","compounds");
x.t("screening","search");
}
