function FileData_Pairs(x)
{
x.t("camod","administration");
x.t("user","usually");
x.t("scientific","correctness");
x.t("evaluates","model");
x.t("editing","work");
x.t("editing","model");
x.t("coordinator","coordinating");
x.t("usually","scientifically");
x.t("entry","scientific");
x.t("scientifically","trained");
x.t("appointed","coordinator");
x.t("flow","information");
x.t("registered","user");
x.t("review","process");
x.t("trained","evaluates");
x.t("editor","appointed");
x.t("editor","registered");
x.t("process","editing");
x.t("administration","roles");
x.t("correctness","editor");
x.t("work","flow");
x.t("model","camod");
x.t("model","editing");
x.t("model","entry");
x.t("model","editor");
x.t("management","screening");
x.t("coordinating","review");
x.t("roles","management");
x.t("screening","model");
}
