function FileData_Pairs(x)
{
x.t("example","communications");
x.t("submitter","obtain");
x.t("camod","administration");
x.t("nature","carried");
x.t("coordinator","information");
x.t("editing","model");
x.t("need","communicate");
x.t("obtain","information");
x.t("review","follow-up");
x.t("review","process");
x.t("communicate","model");
x.t("communications","nature");
x.t("editor","finished");
x.t("may","need");
x.t("assigned","model");
x.t("follow-up","camod");
x.t("follow-up","review");
x.t("follow-up","screener");
x.t("finished","reviewing");
x.t("carried","coordinator");
x.t("process","review");
x.t("information","model");
x.t("information","screening");
x.t("reviewing","assigned");
x.t("administration","roles");
x.t("management","coordinating");
x.t("coordinating","review");
x.t("model","example");
x.t("model","submitter");
x.t("model","editing");
x.t("model","may");
x.t("screener","editor");
x.t("roles","management");
x.t("screening","model");
}
