function FileData_Pairs(x)
{
x.t("searching","camod");
x.t("camod","table");
x.t("camod","search");
x.t("camod","database");
x.t("table","contents");
x.t("drug","screening");
x.t("mode","camod");
x.t("mode","advanced");
x.t("contents","search");
x.t("advanced","search");
x.t("simple","search");
x.t("results","saving");
x.t("overview","camod");
x.t("introduces","procedures");
x.t("search","drug");
x.t("search","mode");
x.t("search","simple");
x.t("search","results");
x.t("search","overview");
x.t("search","query");
x.t("procedures","searching");
x.t("section","introduces");
x.t("section","include");
x.t("database","searching");
x.t("database","search");
x.t("database","section");
x.t("database","topics");
x.t("include","camod");
x.t("saving","search");
x.t("query","drug");
x.t("topics","section");
x.t("screening","search");
}
