function FileData_Pairs(x)
{
x.t("example","screener");
x.t("camod","example");
x.t("camod","administration");
x.t("coordinator","coordinating");
x.t("checks","model");
x.t("reject","model");
x.t("assignment","information");
x.t("entry","appropriate");
x.t("entry","screener");
x.t("images","associated");
x.t("appointed","coordinator");
x.t("flow","comments");
x.t("review","process");
x.t("inappropriate","images");
x.t("comments","assignment");
x.t("process","screening");
x.t("appropriate","camod");
x.t("administration","roles");
x.t("work","flow");
x.t("model","camod");
x.t("model","entry");
x.t("model","inappropriate");
x.t("model","screener");
x.t("model","screening");
x.t("management","screening");
x.t("coordinating","review");
x.t("screener","checks");
x.t("screener","reject");
x.t("screener","appointed");
x.t("associated","model");
x.t("roles","management");
x.t("screening","work");
x.t("screening","model");
}
