function FileData_Pairs(x)
{
x.t("captures","information");
x.t("transgene","associated");
x.t("description","captures");
x.t("description","genetic");
x.t("description","submitting");
x.t("description","include");
x.t("induced","mutation");
x.t("line","mutations");
x.t("interventions","capture");
x.t("categories","genetic");
x.t("genetic","description");
x.t("editing","models");
x.t("mutations","inherited");
x.t("capture","information");
x.t("comparison","carcinogenic");
x.t("inherited","next");
x.t("mutation","spontaneous");
x.t("modification","induced");
x.t("segment","targeted");
x.t("next","generation");
x.t("targeted","modification");
x.t("changes","animals");
x.t("submitting","editing");
x.t("animals","heritable");
x.t("spontaneous","mutation");
x.t("heritable","categories");
x.t("include","transgene");
x.t("germ","line");
x.t("models","genetic");
x.t("expression","genomic");
x.t("carcinogenic","interventions");
x.t("information","changes");
x.t("information","germ");
x.t("generation","comparison");
x.t("associated","expression");
x.t("genomic","segment");
}
