function FileData_Pairs(x)
{
x.t("camod","user");
x.t("camod","coordinator");
x.t("camod","administration");
x.t("user","camod");
x.t("user","assigned");
x.t("user","management");
x.t("coordinator","information");
x.t("assignment","camod");
x.t("assignment","besides");
x.t("assignment","roles");
x.t("registered","user");
x.t("simply","registered");
x.t("assigned","roles");
x.t("information","administration");
x.t("besides","simply");
x.t("administration","user");
x.t("administration","roles");
x.t("management","roles");
x.t("roles","camod");
x.t("roles","assignment");
x.t("roles","management");
x.t("roles","roles");
}
