function FileData_Pairs(x)
{
x.t("camod","administration");
x.t("reject","comment");
x.t("reject","record");
x.t("overview","screener");
x.t("tasks","scan");
x.t("perform","following");
x.t("completed","records");
x.t("records","appropriateness");
x.t("record","scan");
x.t("functions","overview");
x.t("comments","appropriateness");
x.t("scan","comments");
x.t("scan","submitted");
x.t("appropriateness","approve");
x.t("submitted","completed");
x.t("administration","functions");
x.t("administration","administration");
x.t("following","tasks");
x.t("screener","camod");
x.t("screener","perform");
x.t("screener","screener");
x.t("approve","reject");
}
