function FileData_Pairs(x)
{
x.t("searching","camod");
x.t("four","drug");
x.t("trials","searching");
x.t("trials","data");
x.t("trials","clinical");
x.t("camod","database");
x.t("drug","screening");
x.t("program","(ctep)");
x.t("obtained","via");
x.t("objects","nci");
x.t("via","cabio");
x.t("(ctep)","physician");
x.t("biomedical","data");
x.t("search","four");
x.t("search","options");
x.t("cancer","therapy");
x.t("cabio","biomedical");
x.t("options","clinical");
x.t("database","drug");
x.t("physician","data");
x.t("evaluation","program");
x.t("data","obtained");
x.t("data","objects");
x.t("data","query");
x.t("query","(pdq)");
x.t("nci","cancer");
x.t("therapy","evaluation");
x.t("screening","search");
x.t("clinical","trials");
}
