function FileData_Pairs(x)
{
x.t("camod","administration");
x.t("dialog","box");
x.t("open","dialog");
x.t("coordinator","camod");
x.t("coordinator","coordinator");
x.t("coordinator","click");
x.t("coordinator","models");
x.t("assignment","coordinator");
x.t("assignment","comments");
x.t("assignment","models");
x.t("assign","button");
x.t("box","assignments");
x.t("needing","editor");
x.t("needing","screener");
x.t("button","(s)");
x.t("comments","needing");
x.t("editor","assignment");
x.t("click","associated");
x.t("models","needing");
x.t("(s)","open");
x.t("administration","administration");
x.t("administration","roles");
x.t("screener","assignment");
x.t("associated","assign");
x.t("roles","coordinator");
}
