function FileData_Pairs(x)
{
x.t("searching","camod");
x.t("trials","searching");
x.t("trials","populated");
x.t("trials","pre-clinical");
x.t("camod","database");
x.t("drug","screening");
x.t("stored","camod");
x.t("populated","data");
x.t("pre-clinical","trials");
x.t("search","in-vivo");
x.t("database","drug");
x.t("in-vivo","anti-tumor");
x.t("anti-tumor","screening");
x.t("data","stored");
x.t("data","pre-clinical");
x.t("screening","search");
x.t("screening","data");
}
