package gov.nih.nci.camod.biodbnet;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * bioDBnet service = new bioDBnet();
 * BioDBnetPortType portType = service.getBioDBnetPort();
 * portType.getInputs(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "bioDBnet", targetNamespace = "urn:bioDBnet", wsdlLocation = "http://biodbnet.abcc.ncifcrf.gov/webServices/bioDBnet.wsdl")
public class BioDBnet extends Service {

	private final static URL BIODBNET_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(gov.nih.nci.camod.biodbnet.BioDBnet.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = gov.nih.nci.camod.biodbnet.BioDBnet.class.getResource(".");
			url = new URL(baseUrl,
					"http://biodbnet.abcc.ncifcrf.gov/webServices/bioDBnet.wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://biodbnet.abcc.ncifcrf.gov/webServices/bioDBnet.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		BIODBNET_WSDL_LOCATION = url;
	}

	public BioDBnet(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public BioDBnet() {
		super(BIODBNET_WSDL_LOCATION, new QName("urn:bioDBnet", "bioDBnet"));
	}

	/**
	 * 
	 * @return returns BioDBnetPortType
	 */
	@WebEndpoint(name = "bioDBnetPort")
	public BioDBnetPortType getBioDBnetPort() {
		return super.getPort(new QName("urn:bioDBnet", "bioDBnetPort"),
				BioDBnetPortType.class);
	}

}
