package gov.nih.nci.camod.biodbnet;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "bioDBnetPortType", targetNamespace = "urn:bioDBnet")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface BioDBnetPortType {

	/**
	 * Gets all possible bioDBnet input identifiers
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String getInputs();

	/**
	 * Gets all the outputs for an input identifier
	 * 
	 * @param input
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String getOutputsForInput(
			@WebParam(name = "input", partName = "input") String input);

	/**
	 * Gets all the direct path outputs for an input identifier
	 * 
	 * @param input
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String getDirectOutputsForInput(
			@WebParam(name = "input", partName = "input") String input);

	/**
	 * bioDBnet db2db - biological identifier conversions
	 * 
	 * @param db2DbParams
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "db2db")
	@WebResult(partName = "return")
	public String db2Db(
			@WebParam(name = "db2dbParams", partName = "db2dbParams") Db2DbParams db2DbParams);

	/**
	 * bioDBnet dbReport - detailed annotation reports
	 * 
	 * @param dbReportParams
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String dbReport(
			@WebParam(name = "dbReportParams", partName = "dbReportParams") DbReportParams dbReportParams);

	/**
	 * bioDBnet dbFind - Finds the type of biological identifiers
	 * 
	 * @param dbFindParams
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String dbFind(
			@WebParam(name = "dbFindParams", partName = "dbFindParams") DbFindParams dbFindParams);

	/**
	 * bioDBnet dbWalk - biological identifier conversions following custom
	 * paths
	 * 
	 * @param dbWalkParams
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String dbWalk(
			@WebParam(name = "dbWalkParams", partName = "dbWalkParams") DbWalkParams dbWalkParams);

	/**
	 * bioDBnet dbOrtho - identifier conversions across species
	 * 
	 * @param dbOrthoParams
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String dbOrtho(
			@WebParam(name = "dbOrthoParams", partName = "dbOrthoParams") DbOrthoParams dbOrthoParams);

}
