function  WWHBookData_MatchTopic(P)
{
var C=null;
if(P=="register_user_help")C="About caMOD.2.4.html#1069005";
if(P=="login_page_help")C="About caMOD.2.5.html";
if(P=="user_settings_help")C="About caMOD.2.6.html#1074656";
if(P=="whatsnew_help")C="About caMOD.2.8.html";
if(P=="submit_edit_models_help")C="About caMOD.2.9.html";
if(P=="model_status_help")C="Submit and Edit Models.3.5.html#1105598";
if(P=="model_characteristics_help")C="Submit and Edit Models.3.7.html#1070098";
if(P=="data_tree_help")C="Submit and Edit Models.3.8.html";
if(P=="transgene_help")C="Submit and Edit Models.3.9.html#1091588";
if(P=="associated_expression_help")C="Submit and Edit Models.3.11.html";
if(P=="genomic_segment_help")C="Submit and Edit Models.3.12.html#1070686";
if(P=="targeted_modification_help")C="Submit and Edit Models.3.13.html#1070866";
if(P=="induced_mutation_help")C="Submit and Edit Models.3.14.html";
if(P=="spontaneous_mutation_help")C="Submit and Edit Models.3.15.html";
if(P=="chemical_drug_help")C="Submit and Edit Models.3.16.html#1074507";
if(P=="environmental_factor_help")C="Submit and Edit Models.3.17.html";
if(P=="gene_delivery_help")C="Submit and Edit Models.3.18.html";
if(P=="growth_factor_help")C="Submit and Edit Models.3.19.html";
if(P=="hormone_help")C="Submit and Edit Models.3.20.html";
if(P=="nutritional_factor_help")C="Submit and Edit Models.3.21.html";
if(P=="radiation_help")C="Submit and Edit Models.3.22.html";
if(P=="surgery_help")C="Submit and Edit Models.3.23.html";
if(P=="viral_treatment_help")C="Submit and Edit Models.3.24.html";
if(P=="transient_interference_help")C="Submit and Edit Models.3.25.html";
if(P=="publication_help")C="Submit and Edit Models.3.26.html";
if(P=="histopathology_help")C="Submit and Edit Models.3.27.html#1084666";
if(P=="clinical_marker_help")C="Submit and Edit Models.3.28.html#1085296";
if(P=="associated_metastasis_help")C="Submit and Edit Models.3.29.html#1085855";
if(P=="therapy_help")C="Submit and Edit Models.3.30.html";
if(P=="cell_lines_help")C="Submit and Edit Models.3.31.html";
if(P=="images_help")C="Submit and Edit Models.3.32.html#1087837";
if(P=="microarray_data_help")C="Submit and Edit Models.3.34.html";
if(P=="model_availability_help")C="Submit and Edit Models.3.35.html#1088437";
if(P=="xenograft_transplant_help")C="Submit and Edit Models.3.36.html";
if(P=="help_searching_help")C="caMOD searches.4.1.html#1068738";
if(P=="toc_help")C="caMOD searches.4.2.html";
if(P=="simple_search_help")C="caMOD searches.4.3.html#1068866";
if(P=="advanced_search_help")C="caMOD searches.4.5.html#1069037";
if(P=="search_results_help")C="caMOD searches.4.7.html#1069391";
if(P=="saving_search_query_help")C="caMOD searches.4.8.html#1073230";
if(P=="search_query_history_help")C="caMOD searches.4.9.html#1073310";
if(P=="customizing_search_results_help")C="caMOD searches.4.10.html#1073802";
if(P=="drug_screening_help")C="caMOD searches.4.11.html#1069560";
if(P=="administration_roles_help")C="caMOD admin.5.5.html#1073499";
if(P=="edit_user_help")C="caMOD admin.5.9.html";
if(P=="add_user_help")C="caMOD admin.5.10.html#1073923";
if(P=="assigning_screener_help")C="caMOD admin.5.11.html#1074083";
if(P=="assigning_an_editor_help")C="caMOD admin.5.13.html#1072472";
if(P=="roles_management_help")C="caMOD admin.5.17.html#1072713";
if(P=="request_information_help")C="caMOD admin.5.24.html";
if(P=="models_assignment_help")C="caMOD admin.5.25.html";
if(P=="screening_model_help")C="caMOD admin.5.26.html#1072939";
if(P=="comments_assignment_help")C="caMOD admin.5.28.html#1073124";
return C;
}
