/*
 * UtilSuite.java
 * JUnit based test
 *
 * Created on November 22, 2005, 2:14 PM
 */

package unit.gov.nih.nci.camod.util;

import junit.framework.*;

/**
 *
 * @author piparom
 */
public class UtilSuite extends TestCase {
  
  public UtilSuite(String testName) {
    super(testName);
  }

  protected void setUp() throws Exception {
  }

  protected void tearDown() throws Exception {
  }

  /**
   * suite method automatically generated by JUnit module
   */

  /**
   * suite method automatically generated by JUnit module
   */
  public static Test suite() {
    TestSuite suite = new TestSuite("UtilSuite");
    suite.addTest(unit.gov.nih.nci.camod.util.AuthenticationFilterTest.suite());
    suite.addTest(unit.gov.nih.nci.camod.util.ConvertUtilTest.suite());
    suite.addTest(unit.gov.nih.nci.camod.util.CurrencyConverterTest.suite());
    suite.addTest(unit.gov.nih.nci.camod.util.CustomRequestProcessorTest.suite());
    suite.addTest(unit.gov.nih.nci.camod.util.DateConverterTest.suite());
    suite.addTest(unit.gov.nih.nci.camod.util.DateUtilTest.suite());
    suite.addTest(unit.gov.nih.nci.camod.util.DrugScreenResultTest.suite());
    suite.addTest(unit.gov.nih.nci.camod.util.DuplicateUtilTest.suite());
    suite.addTest(unit.gov.nih.nci.camod.util.EvsTreeUtilTest.suite());
    suite.addTest(unit.gov.nih.nci.camod.util.FtpUtilTest.suite());
    suite.addTest(unit.gov.nih.nci.camod.util.GUIDGeneratorTest.suite());
    suite.addTest(unit.gov.nih.nci.camod.util.HashCodeUtilTest.suite());
    suite.addTest(unit.gov.nih.nci.camod.util.LDAPUtilTest.suite());
    suite.addTest(unit.gov.nih.nci.camod.util.LabelValueTest.suite());
    suite.addTest(unit.gov.nih.nci.camod.util.MailUtilTest.suite());
    suite.addTest(unit.gov.nih.nci.camod.util.PopulatePubMedUtilTest.suite());
    suite.addTest(unit.gov.nih.nci.camod.util.RandomGUIDTest.suite());
    suite.addTest(unit.gov.nih.nci.camod.util.StringUtilTest.suite());
    suite.addTest(unit.gov.nih.nci.camod.util.TimestampConverterTest.suite());
    return suite;
  }
  
}
