function FileData_Pairs(x)
{
x.t("camod","user");
x.t("camod","permissions");
x.t("camod","coordinator.");
x.t("camod","administration");
x.t("user","camod");
x.t("user","assigned");
x.t("user","management");
x.t("assignment","camod");
x.t("assignment","besides");
x.t("assignment","roles");
x.t("overview","user");
x.t("permissions","administration");
x.t("functions","overview");
x.t("registered","user");
x.t("simply","registered");
x.t("assigned","roles");
x.t("coordinator.","information");
x.t("information","camod");
x.t("besides","simply");
x.t("administration","functions");
x.t("administration","administration");
x.t("administration","roles");
x.t("management","roles");
x.t("roles","camod");
x.t("roles","assignment");
x.t("roles","management");
x.t("roles","roles");
}
