function FileData_Pairs(x)
{
x.t("camod","submitting");
x.t("tree","genetic");
x.t("description","carcinogenic");
x.t("interventions","transient");
x.t("genetic","description");
x.t("editing","models.");
x.t("editing","models");
x.t("navigating","data");
x.t("transient","interference");
x.t("histopathology","therapy");
x.t("images","microarray");
x.t("availability","transplant/xenograft");
x.t("include:","submitting");
x.t("introduces","processes");
x.t("lines","images");
x.t("cell","lines");
x.t("models.","topics");
x.t("publications","histopathology");
x.t("processes","camod");
x.t("section","include:");
x.t("section","introduces");
x.t("submitting","editing");
x.t("submitting","models");
x.t("microarray","data");
x.t("interference","publications");
x.t("models","navigating");
x.t("models","section");
x.t("models","submitting");
x.t("carcinogenic","interventions");
x.t("data","tree");
x.t("data","model");
x.t("topics","section");
x.t("model","availability");
x.t("therapy","cell");
}
