function FileData_Pairs(x)
{
x.t("editors","assign");
x.t("camod","administration");
x.t("coordinator","camod");
x.t("coordinator","coordinator");
x.t("coordinator","perform");
x.t("new","users");
x.t("add","new");
x.t("assign","comments");
x.t("assign","models");
x.t("overview","coordinator");
x.t("perform","following");
x.t("functions","overview");
x.t("comments","screener");
x.t("editor","assign");
x.t("tasks:","add");
x.t("models","editor");
x.t("models","screener");
x.t("administration","functions");
x.t("administration","administration");
x.t("users","appoint");
x.t("appoint","editors");
x.t("appoint","screeners");
x.t("following","tasks:");
x.t("screeners","appoint");
x.t("screener","assign");
}
