function FileData_Pairs(x)
{
x.t("searching","camod");
x.t("camod","database.");
x.t("camod","administration");
x.t("user","management");
x.t("overview","administration");
x.t("include:","administration");
x.t("introduces","procedures");
x.t("database.","topics");
x.t("procedures","searching");
x.t("functions","overview");
x.t("section","include:");
x.t("section","introduces");
x.t("administration","camod");
x.t("administration","functions");
x.t("administration","section");
x.t("administration","roles");
x.t("topics","section");
x.t("management","roles");
x.t("roles","user");
x.t("roles","management");
}
